### ISSUE TITLE
crash during initialization with osmesa

### ISSUE THREAD

**Issue by burlen** [OpenSWR/openswr#3]
I'd like to start using this on systems without X11, however there is a crash during context creation. See the stack trace below. I could reproduce this with VTK master branch by running ctest -R LoadOpenGL --verbose, using both LD_PRELOAD and the VTK built only with openswr.

855: =========================================================
855: Process id 13591 Caught SIGILL at 0x7f057e297a0d illegal operand
855: Program Stack:
855: 0x31f0c358f0 : ??? [(???) ???:-1]
855: 0x7f057e297a0d : OGL::MaintainMatrixInfoInvariant(OGL::State&) [(libGL.so) ???:-1]
855: 0x7f057e2a600a : OGL::Initialize(OGL::State&) [(libGL.so) ???:-1]
855: 0x7f057e2b237d : OSMesaCreateContext [(libGL.so) ???:-1]
855: 0x7f05779fa63e : vtkOSOpenGLRenderWindow::CreateOffScreenWindow(int, int) [(libvtkRenderingOpenGL-6.3.so.1) ???:-1]
855: 0x7f05779f9f2d : vtkOSOpenGLRenderWindow::Start() [(libvtkRenderingOpenGL-6.3.so.1) ???:-1]
855: 0x7f05793ae2b0 : vtkRenderWindow::DoStereoRender() [(libvtkRenderingCore-6.3.so.1) ???:-1]
855: 0x7f05793af4e7 : vtkRenderWindow::DoFDRender() [(libvtkRenderingCore-6.3.so.1) ???:-1]
855: 0x7f05793af0fe : vtkRenderWindow::DoAARender() [(libvtkRenderingCore-6.3.so.1) ???:-1]
855: 0x7f05793ae6c5 : vtkRenderWindow::Render() [(libvtkRenderingCore-6.3.so.1) ???:-1]
855: 0x40ce6a : LoadOpenGLExtension(int, char**) [(vtkRenderingOpenGLCxxTests) ???:-1]
855: 0x40bd73 : main [(vtkRenderingOpenGLCxxTests) ???:-1]
855: 0x31f0c21d65 : __libc_start_main [(libc.so.6) ???:-1]
855: 0x40c7b9 : ??? [(???) ???:-1]
855: =========================================================

**Comment by BruceCherniak** [comment]
This stack trace is the result of compiling OpenSWR for AVX2 on an AVX-class processor.  We are working with Burlen directly via email on additional OSMesa issues.
