### ISSUE TITLE
Cannot build on our LLNL cluster

### ISSUE THREAD

**Issue by wealthychef1** [OpenSWR/openswr#4]
CMAKE_BUILD_TYPE                *Release                                                                                                             
 CMAKE_INSTALL_PREFIX            */usr/local                                                                                                          
 COMPILER                        *gcc                                                                                                                 
 LLVM_CONFIG                     */usr/bin/llvm-config                                                                                                
 TARGET_ARCH                     *CORE-AVX2                                                                                                           

No matter which TARGET_ARCH I try, I get errors resembling this: 
rcook@rzgpu2 (build ): make
Scanning dependencies of target core
[  2%] Building CXX object core/CMakeFiles/core.dir/api.cpp.o
/g/g0/rcook/current_projects/eris/lclocal/public/openswr/OpenSWR-openswr-9f1f442/core/api.cpp:1: error: bad value (core-avx2) for -march= switch
/g/g0/rcook/current_projects/eris/lclocal/public/openswr/OpenSWR-openswr-9f1f442/core/api.cpp:1: error: bad value (core-avx2) for -mtune= switch
make[2]: *** [core/CMakeFiles/core.dir/api.cpp.o] Error 1
make[1]: *** [core/CMakeFiles/core.dir/all] Error 2
make: *** [all] Error 2

Here is our system info: 
rcook@rzgpu2 (build ): uname -a
Linux rzgpu2 2.6.32-504.12.2.2chaos.ch5.3.x86_64 #1 SMP Fri Mar 20 13:20:55 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux

Any hope for us?

**Comment by wealthychef1** [comment]
i was able to get things to build by toggling advanced options and pointing at a newer C++ compiler, generating the makefiles, then doing this because we don't have a generic "python3" in our environment:  

sed -i'' s/python3/python3-3.4.2/g ./ogldriver/CMakeFiles/ogldriver.dir/build.make

**Comment by wealthychef1** [comment]
Final observation:  performance is lower than that just using GLX on our network so no obvious benefit.  I'm wondering what the major use case is for this.  Perhaps to allow VNC users access to OpenGL?

**Comment by BruceCherniak** [comment]
Hi,

I apologize for any difficulty you had building the source; but, we appreciate you spending the time to evaluate OpenSWR.  We'd like to understand more about your system architecture and use case; and to share with you some of our thoughts and directions.  If you could email me, we can discuss further.

Thanks,
Bruce
